name: CI

on: [push]

jobs:
    eslint-run:
        runs-on: ubuntu-latest

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: Checkout
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
            - name: Install modules
              run: yarn
            - name: Run ESLint
              run: yarn run eslint . --ext .js,.jsx,.ts,.tsx
