name: CI

on:
    [push, pull_request]
    # Triggers the workflow on push or pull request events on any branch

jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
            - name: Install modules
              run: yarn
            - name: Run ESLint
              run: yarn run eslint . --ext .js,.jsx,.ts,.tsx
